### ISSUE TITLE
You should not get a "Last chance to block" if you incorrectly challenge an assassination against you.

### ISSUE THREAD

**Issue by jtherrmann** [octachrome/treason#23]
If player 1 has the assassin and attempts to assassinate player 2, and player 2 challenges, player 1 exchanges the assassin for a new card and player 2 loses a card for the unsuccessful challenge, and then player 2 gets a "Last chance to block". According to my reading of the Coup rules, player 2 should automatically lose a card from the challenge and another card from being assassinated, with no last chance to block.

**Comment by octachrome** [comment]
I'm not sure I agree. The rules say:
> If a player wins a challenge by showing the relevant character card... Then the action or counteraction is resolved.

I think "the action is resolved" implies that you follow the normal rules for the action, i.e. the player being assassinated can claim to have the Contessa and block. If this were not true, I think the rules would say something like "after a failed challenge, the challenging player forfeits the right to block the action."

But I'm open to persuasion...

**Comment by jtherrmann** [comment]
I think your interpretation is correct as long as the player who issued the challenge is not the player being assassinated. For example, if player 1 has the assassin and attempts to assassinate player 2, and player 3 challenges, then player 1 should exchange the assassin for a new card (assuming they choose to reveal the assassin), player 3 should lose a card, and player 2 should still have the option to block.

However, in the case where player 2 challenges the assassination, this section of the rules makes me think that player 2 should automatically lose both cards:

> **Note: Double Dangers of Assassination**
>
> It is possible to lose 2 influence in one turn if you unsuccessfully defend against an assassination. For example, if you challenge an assassin used against you and lose the challenge, you will lose 1 influence for the lost challenge and then 1 influence for the successful assassination.

There is no mention of having a chance to block after losing the challenge. It simply says: "you will lose 1 influence for the lost challenge and then 1 influence for the successful assassination", implying that the assassination is automatically successful if you lose the challenge. But I agree the rules could certainly be more clear on this point.

**Comment by octachrome** [comment]
@JackieNiebling What do you think about this?

**Comment by JackieNiebling** [comment]
The section about "Double Dangers of Assassination" specifically mentions an unsuccessful defence against an assassination. The rules state that challenges are resolved first before actions or counteractions.

As I read the rules, this means if player 1 assassinates player 2 (announces the intention to do so, the intended target and pays the money) and player 2 challenges the assassination (and loses, because player 1 has the assassin influence), player 2 must immediately reveal (lose) an influence. At this point, the assassination _action is not yet successful though,_ as player 2 can still **counteract** (by claiming a contessa.)

I believe jtherrmann's original interpretation of the rule is wrong. An opening line in the rules state that: "If an action is not challenged or counteracted, the action automatically succeeds. Challenges are resolved first before any action or counteraction is resolved." So in our case, first the action is challenged and then it is counteracted. Who does the challenging is immaterial. There is nothing that suggests that a player who defeated a challenge while assassinating is automatically "successful" in the assassination.

**Comment by jtherrmann** [comment]
@JackieNiebling Interesting. I interpreted the line "Challenges are resolved first before any action or counteraction is resolved" to mean that you may challenge an action or you may challenge a counteraction, and the challenge is resolved first before that action or counteraction is resolved. I did not interpret it to mean that if you challenge an action, the challenge is resolved and then you may still counteract that action.

Under the "Challenges" section of the rules, it says that "Whoever loses the challenge immediately loses an influence....Then the action or counteraction is resolved." So I think that the line "Challenges are resolved first before any action or counteraction is resolved" simply means that if an action or counteraction is challenged, the challenge is resolved before that action or counteraction.

I think I have been assuming that each person must choose whether to challenge or counteract an action, but not both. Under the "Game Play" section of the rules, it says that "other players have an opportunity to challenge or counteract that action." I interpreted the "or" as an exclusive "or", meaning that each player can challenge or counteract, but not both.

For example, I would assume that if player 1 steals from player 2, and player 3 unsuccessfully challenges player 1, then player 3 loses a card, player 1 gets a new card, and then player 2 still has the chance to block the steal. However, if player 2 unsuccessfully challenges player 1, then player 2 does not get a last chance to block, because player 2 has already chosen to challenge, and they cannot both challenge and counteract the same action.

Again, I think my argument mostly rests on the use of the phrase "challenge or counteract" in the rules, and my interpretation of the "or" as meaning "one or the other." I also think it's more fun if each person has to choose whether they want to challenge or block an action, because it raises the stakes and makes the game feel more deadly, but that's just me.

I do not think there is anything in the rules that would explicitly clarify this issue. I am somewhat tempted to contact the game's authors for clarification.

**Comment by jtherrmann** [comment]
I also think that the line, "For example, if you challenge an assassin used against you and lose the challenge, you will lose 1 influence for the lost challenge and then 1 influence for the successful assassination" makes it sound like you **will** inevitably lose 2 influence if you unsuccessfully challenge an assassination against you. I believe the authors would have mentioned the last chance to block if that is what they intended. Note that, under my interpretation of the rules, if another player unsuccessfully challenged the assassination against you, then you would still have a last chance to block, because you were not the one who issued the challenge.
